print("Type a name")
name = input()
print("Type a place")
place = input()
print("Type a verb")
verb = input()
print("Type a noun")
noun = input()
print(name ,"went to the", place , verb , "And bought a", noun)